### ISSUE TITLE
Game in Infinite Loop

### ISSUE THREAD

**Issue by senor-coder** [Naren-Jegan/ConnectFourGame#3]
The project ends in an infinite loop. Please investigate ASAP on this.

**Comment by Naren-Sridharan** [comment]
The Project ended in an infinite loop because you had changed the ordering of one of the enum "GameState".. No some other small issues have also been rectified in the latest commit.. Please check and say if there are any issues. Thanks.

**Comment by senor-coder** [comment]
Also can you start collecting all the moves in a vector or a list, this list will be returned by gameController::Play , and in the main function (better a separate module) to serialize this list to a json.

**Comment by Naren-Sridharan** [comment]
Done, Seperate module but not in main function
