### ISSUE TITLE
Remove warnings

### ISSUE THREAD

**Issue by senor-coder** [Naren-Jegan/ConnectFourGame#4]
Below is  the output of warnings generated by running the makefile. Take a look in to it.

Creating directories
Beginning release build
Compiling: src/Bot.cpp -> build/release/Bot.o
     Compile time: 00:00:00
Compiling: src/ComputerBot.cpp -> build/release/ComputerBot.o
In file included from src/ComputerBot.cpp:1:0:
include/ComputerBot.h:10:5: warning: unused parameter 'U' [-Wunused-parameter]
     CompBot(CompBot const &U):Bot(Constants::COMP){};
     ^
     Compile time: 00:00:01
Compiling: src/Constants.cpp -> build/release/Constants.o
     Compile time: 00:00:00
Compiling: src/ContestantBot.cpp -> build/release/ContestantBot.o
In file included from src/ContestantBot.cpp:1:0:
include/ContestantBot.h:9:5: warning: unused parameter 'U' [-Wunused-parameter]
     UserBot(UserBot const &U):Bot(Constants::USER){};
     ^
     Compile time: 00:00:00
Compiling: src/GameController.cpp -> build/release/GameController.o
     Compile time: 00:00:00
Compiling: src/NuclearCell.cpp -> build/release/NuclearCell.o
     Compile time: 00:00:00
Compiling: src/NuclearReactor.cpp -> build/release/NuclearReactor.o
src/NuclearReactor.cpp:22:1: warning: unused parameter 'player' [-Wunused-parameter]
 NuclearReactor::NuclearReactor(Constants::PlayerType player){
 ^
     Compile time: 00:00:01
Compiling: src/main.cpp -> build/release/main.o
In file included from src/main.cpp:1:0:
include/ComputerBot.h:10:5: warning: unused parameter 'U' [-Wunused-parameter]
     CompBot(CompBot const &U):Bot(Constants::COMP){};
     ^
In file included from src/main.cpp:2:0:
include/ContestantBot.h:9:5: warning: unused parameter 'U' [-Wunused-parameter]
     UserBot(UserBot const &U):Bot(Constants::USER){};
     ^
     Compile time: 00:00:00
Linking: bin/release/main
     Link time: 00:00:00
Making symlink: main -> bin/release/main
Total build time: 00:00:02

**Comment by Naren-Sridharan** [comment]
Warnings should have been removed. Please, check and confirm. Thanks.
